### PR TITLE
checking message nonce and block hash

### PR DESCRIPTION
**Pull request by hopeyen**
Added nonce and blockhash to the message such that 
- sender cannot inject a message into the past with strictly increasing nonce from the senders (nonce map still needs to be stored)
- sender cannot make a message for the future by checking blockhash

### CODE REVIEW

**Review by cargopete — APPROVED** [review]
awesome stuff 💯

**Review by cargopete — COMMENTED** [review]
🤔  For some reason it kept the "1" nonce as `prevNonce` and didn't update with the "2", then disregarded all the next ones as invalid (just approved the "2")

Screenshot 2022-09-02 at 15 06 51
image
Screenshot 2022-09-02 at 15 06 23

**Comment by axiomatic-aardvark** [comment]
Also it starts with this, not sure if it's expected 😅 
image

**Comment by cargopete** [comment]
Seems to be happening pretty randomly, this time it didn't even update to "1" :/
image

**Comment by hopeyen** [comment]
> Seems to be happening pretty randomly, this time it didn't even update to "1" :/ image

ah I see, this is the case I was sort of concerned about. We said to only update to the next nonce and not to allow messengers to skip messages, but if we as a receiver somehow missed a message in transmission, we will not think future messages are valid anymore. If we go off network for a while and then come back, other messengers have already moved on (for now nonce directory reset every instance so that's fine, but I think we want to store it in future).

we can fix this by letting nonce update to later nonces, not just the very next one, but would be less secure. What do you think?

**Comment by cargopete** [comment]
> > Seems to be happening pretty randomly, this time it didn't even update to "1" :/ image
> 
> ah I see, this is the case I was sort of concerned about. We said to only update to the next nonce and not to allow messengers to skip messages, but if we as a receiver somehow missed a message in transmission, we will not think future messages are valid anymore. If we go off network for a while and then come back, other messengers have already moved on (for now nonce directory reset every instance so that's fine, but I think we want to store it in future).
> 
> we can fix this by letting nonce update to later nonces, not just the very next one, but would be less secure. What do you think?

Makes total sense, I'd suggest going with the less secure (but more stable) route for now, at least until we move on to using our own Waku nodes and reassessing the issue then

**Pull request merged**
